### ISSUE TITLE
Flagsmith Internal Server Error while trying to update version

### ISSUE THREAD

**Issue by indrakit2** [SolidStateGroup/bullet-train-api#2717]
**Django.request ERROR    Internal Server Error: /api/v1/organisations/1/groups/**

I wanted to update the Flagsmith backend from 2.24.4 to 2.63.0 and the frontend from 2.26.0 to 2.63.0. So that I could have the same version on the frontend and the backend.  After that, I got this exception 
django.request ERROR Internal Server Error: /api/v1/organisations/1/groups/

**To Reproduce**

1. Updated Flagsmith version backend from 2.24.4 to 2.63 and frontend from  2.26.0 to 2.63.0
2. See error

![image](https://github.com/Flagsmith/flagsmith/assets/14870637/87fd10f1-97a6-4791-83f2-e61eaa679fc8)

**Expected behavior**

Flagsmith was successfully updated.

**Screenshots**

**How are you running Flagsmith?**

- [ ] Self Hosted with Kubernetes

**Comment by khvn26** [comment]
Thanks for reporting this, @indrakit2! While we try to reproduce this, could you please share the full log including the full error traceback?

**Comment by matthewelwell** [comment]
@indrakit2 Please can you also provide better reproduction steps? The ones provided are not adequate for us to reproduce the error. What actions did you take via the API or the dashboard to reproduce the error? Is this occurring every time you perform a particular action?

**Comment by indrakit2** [comment]
> Thanks for reporting this, @indrakit2! While we try to reproduce this, could you please share the full log including the full error traceback?


```
Starting application
[2023-09-04 10:21:13 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-09-04 10:21:13 +0000] [7] [INFO] Listening at: http://0.0.0.0:8000 (7)
[2023-09-04 10:21:13 +0000] [7] [INFO] Using worker: gthread
[2023-09-04 10:21:13 +0000] [8] [INFO] Booting worker with pid: 8
[2023-09-04 10:21:13 +0000] [9] [INFO] Booting worker with pid: 9
[2023-09-04 10:21:13 +0000] [10] [INFO] Booting worker with pid: 10
django.request WARNING  Unauthorized: /api/v1/auth/login/
django.request WARNING  Forbidden: /api/v1/environments/W8PoFjW9Uy43bGAK6ZTzxJ/list-change-requests/
django.request WARNING  Forbidden: /api/v1/environments/W8PoFjW9Uy43bGAK6ZTzxJ/featurestates/
django.request WARNING  Not Found: /api/v1/organisations/1/get-subscription-metadata/
django.request WARNING  Bad Request: /api/v1/projects/1/features/
django.request WARNING  Forbidden: /api/v1/environments/W8PoFjW9Uy43bGAK6ZTzxJ/list-change-requests/
django.request WARNING  Forbidden: /api/v1/environments/W8PoFjW9Uy43bGAK6ZTzxJ/featurestates/
django.request WARNING  Not Found: /api/v1/organisations/1/get-subscription-metadata/
django.request WARNING  Bad Request: /api/v1/projects/1/features/
django.request WARNING  Not Found: /api/v1/organisations/1/get-subscription-metadata/
/opt/venv/lib/python3.10/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'features.workflows.core.models.ChangeRequest'> SoftDeleteQuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/opt/venv/lib/python3.10/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'features.workflows.core.models.ChangeRequest'> SoftDeleteQuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
Exception in thread Thread-104 (create_audit_log_from_historical_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/audit/tasks.py", line 67, in create_audit_log_from_historical_record
    history_instance = model_class.objects.get(history_id=history_instance_id)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
features.models.HistoricalFeature.DoesNotExist: HistoricalFeature matching query does not exist.
```

**Comment by matthewelwell** [comment]
@indrakit2, this is actually an unrelated error. Please provide further information in replication steps as requested.
