### ISSUE TITLE
Health checks no longer test DB migrations

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2803]
We remove this recently - should we re-introduce it?

**Comment by matthewelwell** [comment]
Yes, we definitely should. 

I'm not convinced that we know _exactly_ why it caused us an issue before since the rollback should have worked since the previous version should have had all the migrations it expected to be there. We think that the old container health checks were failing due to the exhaustion of DB connections on the database rather than any migration issues but I'm not currently 100% certain on this. @gagantrivedi may know more.

**Comment by nishant-shah-social** [comment]
Hello Guys, I stumbled upon this issue while searching for something.
We upgraded selfhosted flagsmith from v 2.66 to v2.129 couple of days back. There were no hiccups after the upgrade for around 20 hours or so. But after that we started seeing a sharp spike in errors like below in the flagsmith-api

```ERROR 2024-07-25T08:15:38.010504999Z [resource.labels.containerName: flagsmith-api] health-check ERROR unavailable: Database error
ERROR 2024-07-25T08:15:38.010536493Z [resource.labels.containerName: flagsmith-api] Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs)
ERROR 2024-07-25T08:15:38.010563596Z [resource.labels.containerName: flagsmith-api] ^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-25T08:15:38.010567829Z [resource.labels.containerName: flagsmith-api] File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 200, in connect
ERROR 2024-07-25T08:15:38.010571351Z [resource.labels.containerName: flagsmith-api] self.connection = self.get_new_connection(conn_params)
ERROR 2024-07-25T08:15:38.010575351Z [resource.labels.containerName: flagsmith-api] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-25T08:15:38.010578890Z [resource.labels.containerName: flagsmith-api] File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
ERROR 2024-07-25T08:15:38.010583126Z [resource.labels.containerName: flagsmith-api] return func(*args, **kwargs)
ERROR 2024-07-25T08:15:38.010586424Z [resource.labels.containerName: flagsmith-api] ^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-25T08:15:38.010590238Z [resource.labels.containerName: flagsmith-api] File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
ERROR 2024-07-25T08:15:38.010594044Z [resource.labels.containerName: flagsmith-api] connection = Database.connect(**conn_params)
ERROR 2024-07-25T08:15:38.010598040Z [resource.labels.containerName: flagsmith-api] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-25T08:15:38.010601802Z [resource.labels.containerName: flagsmith-api] File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
ERROR 2024-07-25T08:15:38.010605979Z [resource.labels.containerName: flagsmith-api] conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
ERROR 2024-07-25T08:15:38.010609517Z [resource.labels.containerName: flagsmith-api] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2024-07-25T08:15:38.010615094Z [resource.labels.containerName: flagsmith-api] psycopg2.OperationalError: connection to server at "flagsmith-cloudsqlproxy" (10.X.X.X), port 5432 failed: server closed the connection unexpectedly
ERROR 2024-07-25T08:15:38.010618828Z [resource.labels.containerName: flagsmith-api] This probably means the server terminated abnormally
ERROR 2024-07-25T08:15:38.010622257Z [resource.labels.containerName: flagsmith-api] before or while processing the request.
ERROR 2024-07-25T08:15:38.010625526Z [resource.labels.containerName: flagsmith-api] {}
ERROR 2024-07-25T08:15:38.010628582Z [resource.labels.containerName: flagsmith-api] {}
ERROR 2024-07-25T08:15:38.010631910Z [resource.labels.containerName: flagsmith-api] The above exception was the direct cause of the following exception:
ERROR 2024-07-25T08:15:38.010634947Z [resource.labels.containerName: flagsmith-api] {}
ERROR 2024-07-25T08:15:38.010638227Z [resource.labels.containerName: flagsmith-api] Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/health_check/db/backends.py", line 12, in check_status obj = TestModel.objects.create(title="test")
  {
    "textPayload": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/health_check/db/backends.py\", line 12, in check_status\n    obj = TestModel.objects.create(title=\"test\")"
  }
```

The resource utilization of all the flagsmith components was normal, including the cloud proxy and the database.
However, we observed frequent restarts of our pods and lot of requests timing out.
Looking at the above error logs, any pointers what can cause it?

Regards,
Nishant Shah

**Comment by khvn26** [comment]
@nishant-shah-social Your Cloud SQL Proxy and the database logs should help diagnosing this.
