### ISSUE TITLE
Versioning V2 issues

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3911]
After enabling versioning v2 in staging, I've noticed a couple of issues. The following exceptions are the causes: 

1. This one is seen in the logs for the task processor when trying to build the environment document for the staging environment in the Flagsmith Website project:

```
Traceback (most recent call last):
  File "/app/task_processor/processor.py", line 96, in _run_task
    task.run()
  File "/app/task_processor/models.py", line 66, in run
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/environments/tasks.py", line 24, in rebuild_environment_document
    wrapper.write_environment(environment)
  File "/app/environments/dynamodb/wrappers/environment_wrapper.py", line 34, in write_environment
    self.write_environments([environment])
  File "/app/environments/dynamodb/wrappers/environment_wrapper.py", line 48, in write_environments
    Item=map_environment_to_environment_document(environment),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/util/mappers/dynamodb.py", line 49, in map_environment_to_environment_document
    for field_name, value in map_environment_to_engine(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/util/mappers/engine.py", line 200, in map_environment_to_engine
    environment_feature_states: List["FeatureState"] = _get_prioritised_feature_states(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/util/mappers/engine.py", line 419, in _get_prioritised_feature_states
    if not feature_state.is_live:
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/features/models.py", line 547, in is_live
    return self.environment_feature_version.is_live
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_live'
```

2. [This one](https://flagsmith.sentry.io/issues/5325807963) was seen in sentry when retrieving the flags for an edge identity in the flagsmith admin dashboard.

**Comment by matthewelwell** [comment]
First issue is resolved here: https://github.com/Flagsmith/flagsmith/pull/3913

**Comment by matthewelwell** [comment]
Second issue is resolved here: https://github.com/Flagsmith/flagsmith/pull/3916
