### ISSUE TITLE
Issue with running `handle_api_usage_notifications` when billing started at and ended at is null

### ISSUE THREAD

**Issue by zachaysan** [SolidStateGroup/bullet-train-api#4410]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/task_processor/processor.py", line 96, in _run_task
    task.run()
  File "/usr/local/lib/python3.11/site-packages/task_processor/models.py", line 66, in run
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/organisations/tasks.py", line 125, in handle_api_usage_notifications
    handle_api_usage_notification_for_organisation(organisation)
  File "/app/organisations/task_helpers.py", line 110, in handle_api_usage_notification_for_organisation
    period_starts_at = relativedelta(months=month_delta) + billing_starts_at
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'relativedelta' and 'NoneType'
```

**Comment by zachaysan** [comment]
Fixed in https://github.com/Flagsmith/flagsmith/pull/4440
