### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Waylon-Firework** [SolidStateGroup/bullet-train-api#4568]
```
[root@iZuf68hx5ixwng3gfelqm6Z ~]# docker logs -f flagsmith
Traceback (most recent call last):
  File "/app/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/task_processor/management/commands/runprocessor.py", line 83, in handle
    thread.start()
  File "/usr/lib/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Comment by Waylon-Firework** [comment]
I fixed the issue by adding the "privileged: true" to the docker-compose. 

I don't know the reason for this error.

**Comment by matthewelwell** [comment]
Hi @Waylon-Firework , in future please use the templates provided when creating issues. The information given here is not sufficient for us to be able to investigate this. Please provide further details about how to reproduce. Specifically, we need information about your deployment environment, and a copy of your docker-compose file. Thanks!
