### ISSUE TITLE
not showing admin page 

### ISSUE THREAD

**Issue by maxisam** [SolidStateGroup/bullet-train-api#859]
tried #594 

Doesn't work. The root issue of mine is 

```
helpers.ts:102 Uncaught Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1419605
    at i (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1419708)
    at Wr (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1460345)
    at d (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1469129)
    at m (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1470378)
    at https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1472329
    at Go (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1473558)
    at ta (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1480230)
    at ja (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1493458)
    at Ra (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1493804)
    at fi (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1498472)
    at ci (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1498126)
    at Ia (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1496638)
    at vi (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1505086)
    at bi (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1505140)
    at Oi.render (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1508959)
    at https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1506773
    at yi (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1504220)
    at ki (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1506706)
    at Object.render (https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1509939)
    at https://flagsmith.org.com/static/main.30102d8319aac1c0a761.js:2:1186211
    at a (https://browser.sentry-cdn.com/4.3.0/bundle.min.js:2:79447)
```

**Comment by maxisam** [comment]
Never mind, totally forgot I separated the api and frondend. duh...
